fix(formatter): add support for comments to builtin statement
influxdata/flux pull request #3240
Opened 2020-10-02 22:52 UTC by nathanielc

The builtin statement parsing would loose comments and the formatter
would not reproduce them. This fixes both the parser and formatter in
regards to builtin statements.

Fixes #3239

### Done checklist
- [ ] docs/SPEC.md updated
- [x] Test cases written

2020-10-05 21:00 UTC, Bolladeen approved these changes

2020-10-09 05:08 UTC, adrian-thurston requested changes
Would be good to capture and format comments in front of the colon, as in this commit 3e9e213d0a792c435a1fa4bfaabeb3dadf35c393 It's unlikely someone would put a comment there, but I think it's better to cover all cases. The `id` and the `type-expression` will be covered already because they reuse other parts of the parser.

2020-10-09 15:33 UTC, nathanielc commented
@adrian-thurston Thanks, for the example commit, I have made the changes to preserve any comments on the `colon` token and added appropriate tests.

2020-10-09 17:10 UTC, adrian-thurston approved these changes
Looks good, thanks for the update.

2020-10-09 19:48 UTC, merged