feat(sql): Oracle database support
influxdata/flux pull request #3485
Opened 2021-02-09 12:40 UTC by alespour

This PR adds Oracle database support to `sql` package.

It uses [godror](https://github.com/godror/godror) **c-go** driver and supports _Easy Connect_ string format (https://www.orafaq.com/wiki/EZCONNECT).
Examples:
  * `scott/tiger@sales-server:1521/ORCL`
  *  `scott/tiger@//75.184.3.22:1522/xepdb1`

[Oracle Instant Client](https://www.oracle.com/database/technologies/instant-client.html) is required at runtime. _Client version should match the server, or it should be ensured that timezone files match. Otherwise, errors such as "ORA-01805: possible error in date/time operation" may occur when working with columns of data types with time zone information._

Known issues and/or limitations:
  * `BOOLEAN` type does not exist in Oracle. Output mapping uses most(?) recommended approach (`CHAR(1)`).
  * `INTERVAL` types are scanned to `time.Duration`, but there is no corresponding `flux.ColType` (yet?), so these types are mapped converted to string. However, duration string representation in Flux is nothing like in Oracle, so an attempt to write such value directly to interval type column fails with _"ORA-01867: the interval is invalid"_.

### Done checklist
- [x] Test cases written

2021-02-12 18:08 UTC, timhallinflux commented
fixes #1433

2021-03-12 21:12 UTC, wolffcm requested changes
Hi Ales, having a runtime dependency is a problem for us. We don't have anything like that currently and it would cause maintenance hassles, especially since we need to cross compile for different platforms. A quick check suggests that the source code is not available for Oracle Instant Client.

Would it be possible to use a pure Go solution like [go-ora](https://github.com/sijms/go-ora) instead?

I can see you've put a significant amount of work into this---sorry to throw a wrench in the works here. I really appreciate the consistent quality of your contributions.

2021-03-15 16:22 UTC, alespour commented
@wolffcm I tried `go-ora` driver as underlying driver, I ran into some specific data type issues (I recall timestamps where strangely shifted as if timezone was messed up). I did not invest more time to make it work - I can, gladly.
But what I'm worried more are legal issues. I know that the driver is listed in golang SQL drivers list. But how do these guys know the Oracle protocol, don't they do reverse engineering? Because what I've read, it is private and proprietary...

2021-12-01 18:19 UTC, wolffcm commented
There is no driver that will work with Flux here: one has a runtime dependency, and the other has issues with legality. Sadly there are no plans to support Oracle in Flux at this time.

2021-12-01 18:19 UTC, closed without merging