fix(json): dictionary encoding
influxdata/flux pull request #3606
Opened 2021-04-05 17:51 UTC by alespour

This PR fixes #3603. 

Example:
```
import "json"
attributes = ["region": "EU"]
json.encode(v: attributes)
```

Returns:
```
{"region": "EU"}
```

### Done checklist
- [x] Test cases written

2021-04-05 18:26 UTC, alespour commented
@jsternberg Do you think this makes sense? Thank you.

2021-04-05 20:48 UTC, jsternberg requested changes
Can you add a comment to the spec in the docs folder describing this behavior? It seems fine I just want it to get explicitly documented.

2021-04-05 20:48 UTC, jsternberg commented on stdlib/json/encode.go
> +		d := make(map[string]interface{}, dict.Len())
Can you make a comment about how json only allows string keys? I didn't know that before reading this: https://www.json.org/json-en.html.

2021-04-06 14:11 UTC, alespour commented
> Can you add a comment to the spec in the docs folder describing this behavior? It seems fine I just want it to get explicitly documented.

I'm sorry, do you mean somewhere to SPEC.md or Outputs.md? I'm not sure where such comment fits better.

2021-05-06 13:56 UTC, jsternberg commented
I mean `docs/SPEC.md`. If this function has an entry there, that should be updated to reflect this change.

2021-08-23 16:29 UTC, alespour commented
@jsternberg sorry, this PR fell into oblivion for some time, but now it popped up again in similar context as before. The code updated to current master, `docs/SPEC.md` also updated.

2022-03-11 18:05 UTC, scbrickley commented
Closed in favor of https://github.com/influxdata/flux/pull/4550

2022-03-11 18:05 UTC, closed without merging