fix: Odd behaviour when going over the Go Rust boundary multiple times using JSON serialization.
influxdata/flux pull request #3729
Opened 2021-05-19 14:56 UTC by skartikey

In the `TestCaseStmt` statement, `id` & `block` are missing in the flux file because of which we are getting the following error. 
`format_test.go:206: missing field `id` at line 1 column 3335`
` format_test.go:206: missing field `block` at line 1 column 3335 `

Adding default to struct TestCaseStmt fixes the issue. 

fixes: #3715

2021-05-19 15:09 UTC, nathanielc requested changes
Why do we want a default? Should we instead find out how that data is missing in the first place? Is it because either Rust or Go forgets to serialize the `id` and `block` data into the JSON?

2021-05-19 15:09 UTC, nathanielc commented on libflux/flux-core/src/ast/mod.rs
>      pub id: Identifier,
What's the default for an Identifier?

2021-05-19 15:46 UTC, rockstar requested changes
I'm not sure this is the right solution. Based on the description of the problem and this patch, I would assume that there is a serialization/deserialization step somewhere on the rust boundary that isn't properly handling `id` and `block` properly. I think that's probably what we need to look at, and figure out why that data isn't getting passed back and forth properly.

2021-05-19 15:46 UTC, rockstar commented on libflux/flux-core/src/ast/mod.rs
> +#[derive(Debug, Default, PartialEq, Clone, Serialize, Deserialize)]
I don't think I knew you could derive `Default`. What does it return when you call `Indentifier::default()`?

2021-05-19 16:03 UTC, skartikey commented
@nathanielc @rockstar I have kept this PR as a draft as this is not the final solution. I did narrow down the problem to `TestCaseStmt` where the actual problem is. As mentioned in the standup today, this PR is to make sure I am going in the right direction with the issue. 

Thanks for the suggestions, I will dig more and find out where exactly we are losing the `id` and the `block`.

2021-05-20 21:37 UTC, rockstar approved these changes

2021-05-21 16:01 UTC, nathanielc requested changes
Looks great, request for a new test see below

2021-05-24 09:40 UTC, skartikey commented on ast/ast.go
> +	Block   *Block         `json:"block"`
I have added the test.

2021-05-24 15:09 UTC, nathanielc approved these changes

2021-05-24 15:09 UTC, merged