fix: removed flux wasm crate and moved it to lsp
influxdata/flux pull request #4005
Opened 2021-08-30 19:08 UTC by BarWeiner1

### Done checklist
- [ ] docs/SPEC.md updated
- [ ] Test cases written

2021-08-30 19:11 UTC, nathanielc commented
Are there stale dependencies in the Cargo.toml as a result of this change? Does this mean that the `flux` repo doesn't need any wasm knowledge?

2021-08-30 22:04 UTC, BarWeiner1 commented
I am pretty sure the flux repo no longer needs any wasm knowledge, which dependencies from Cargo.toml can we safely remove because of that?

2021-08-31 21:16 UTC, scbrickley requested changes
Just one change, but other than that this looks fine.

2021-08-31 21:16 UTC, scbrickley commented on Makefile
> -test: test-go test-rust test-flux test-wasm
We don't want to remove this line entirely. This is what CI uses to run tests. We just want to remove `test-wasm` from the end of this line.

2021-09-01 15:24 UTC, scbrickley approved these changes
LGTM

2021-09-01 17:20 UTC, rockstar approved these changes

2021-09-01 17:23 UTC, merged