feat(experimental/record): add get method
influxdata/flux pull request #4049
Opened 2021-09-17 15:14 UTC by alespour

This PR add `get` method, it returns record field or provided default value.

```
import "experimental/record"

obj = { 
   ticks: 11
}

record.get(r: obj, key: "ticks", default: 0)
11

record.get(r: obj, key: "delay", default: -1)
-1
```

### Done checklist
- [ ] Test cases written

2021-09-24 10:46 UTC, alespour commented
I had to fix formatting of flux test files unrelated to this PR in commit f073080.

2021-09-24 10:53 UTC, alespour commented
Unfortunately I have no idea how to check if `key` value was a string literal, @nathanielc, could you please give me a hint? Thank you.

2021-09-28 21:52 UTC, nathanielc commented
@alespour Good question, there isn't currently a way to enforce its a string literal. For now let's just call that out in the docs of the function.

2021-09-29 12:35 UTC, alespour commented
@nathanielc Thank you. I've updated the PR comment with the function docs paragraph. Ready for review now I hope.

2021-10-01 20:49 UTC, nathanielc requested changes
One small change and this is good to go.

2021-10-01 20:49 UTC, nathanielc commented on stdlib/experimental/record/record.flux
> +builtin get : (r: A, key: string, default: B) => B where A: Record
Could you add a link to this issue here https://github.com/influxdata/flux/issues/4073 ? That way we can track the progress on changing/removing this in the future.

2021-10-04 22:41 UTC, nathanielc approved these changes

2021-10-04 22:41 UTC, nathanielc commented
I'll merge once the PR has been rebased of most recent master.

2021-10-05 11:07 UTC, alespour commented
Done, thank you.

2021-10-06 15:53 UTC, merged