feat(docs): start work on alerta docs
influxdata/flux pull request #4225
Opened 2021-11-05 03:50 UTC by pierwill

2021-11-09 18:57 UTC, nathanielc commented on stdlib/contrib/bonitoo-io/alerta/alerta.flux
> +// ```
can you add a `no_run` to this example as we don't want it to try to connect to alerta?

2021-11-09 19:14 UTC, nathanielc approved these changes

2021-11-09 23:58 UTC, sanderson requested changes

2021-11-09 23:58 UTC, sanderson commented on stdlib/contrib/bonitoo-io/alerta/alerta.flux
> +// ```
~~~suggestion
// ```
//
// tags: single notification
//
~~~

2021-11-09 23:58 UTC, sanderson commented on stdlib/contrib/bonitoo-io/alerta/alerta.flux
> +//   })()
`flux fmt`'d

```suggestion
// import "contrib/bonitoo-io/alerta"
// import "influxdata/influxdb/secrets"
// 
// apiKey = secrets.get(key: "ALERTA_API_KEY")
// endpoint = alerta.endpoint(
//     url: "https://alerta.io:8080/alert",
//     apiKey: apiKey,
//     environment: "Production",
//     origin: "InfluxDB",
// )
// 
// crit_events = from(bucket: "example-bucket")
//     |> range(start: -1m)
//     |> filter(fn: (r) => r._measurement == "statuses" and status == "crit")
// 
// crit_events
//     |> endpoint(
//         mapFn: (r) => {
//             return {r with
//                 resource: "example-resource",
//                 event: "example-event",
//                 severity: "critical",
//                 service: r.service,
//                 group: "example-group",
//                 value: r.status,
//                 text: "Status is critical.",
//                 tags: ["ex1", "ex2"],
//                 attributes: {},
//                 type: "exampleAlertType",
//                 timestamp: now(),
//             }
//         },
//     )()
```

2021-11-09 23:58 UTC, sanderson commented on stdlib/contrib/bonitoo-io/alerta/alerta.flux
> +// tags: notification-endpoints
```suggestion
// tags: notification endpoints,transformations
//
```

2021-11-10 21:08 UTC, sanderson requested changes

2021-11-10 21:08 UTC, sanderson commented on stdlib/contrib/bonitoo-io/alerta/alerta.flux
> +// - attributes: (Required) Alert attributes.
```suggestion
// - url: Alerta URL.
// - apiKey: Alerta API key.
// - resource: Resource associated with the alert.
// - event: Event name.
// - environment: Alerta environment.
// 
//   **Valid values**:
//   - `"Production"`
//   - `"Development"`
//   - empty string (`""`) _(default)_
// 
// - severity: Event severity. See [Alerta severities](https://docs.alerta.io/en/latest/api/alert.html#alert-severities).
// - service: List of affected services. Default is `[]`.
// - group: Alerta event group. Default is `""`.
// - value: Event value.  Default is `""`.
// - text: Alerta text description. Default is `""`.
// - tags: List of event tags. Default is `[]`.
// - attributes: Alert attributes.
```

2021-11-10 21:08 UTC, sanderson commented on stdlib/contrib/bonitoo-io/alerta/alerta.flux
> +// - timestamp: time alert was generated. Default is `now()`.
```suggestion
// - origin: Monitoring component.
// - type: Event type. Default is `""`.
// - timestamp: Time alert was generated. Default is `now()`.
```

2021-11-10 21:08 UTC, sanderson commented on stdlib/contrib/bonitoo-io/alerta/alerta.flux
> +// )
`flux fmt`'d

```suggestion
// import "contrib/bonitoo-io/alerta"
// import "influxdata/influxdb/secrets"
// 
// apiKey = secrets.get(key: "ALERTA_API_KEY")
// 
// lastReported = from(bucket: "example-bucket")
//     |> range(start: -1m)
//     |> filter(
//         fn: (r) => r._measurement == "example-measurement" and r._field == "level",
//     )
//     |> last()
//     |> findRecord(fn: (key) => true, idx: 0)
// 
// severity = if lastReported._value > 50 then "warning" else "ok"
// 
// alerta.alert(
//     url: "https://alerta.io:8080/alert",
//     apiKey: apiKey,
//     resource: "example-resource",
//     event: "Example event",
//     environment: "Production",
//     severity: severity,
//     service: ["example-service"],
//     group: "example-group",
//     value: string(v: lastReported._value),
//     text: "Service is ${severity}. The last reported value was ${string(v: lastReported._value)}.",
//     tags: ["ex1", "ex2"],
//     attributes: {},
//     origin: "InfluxDB",
//     type: "exampleAlertType",
//     timestamp: now(),
// )
```

2021-11-10 21:08 UTC, sanderson commented on stdlib/contrib/bonitoo-io/alerta/alerta.flux
> +// - origin: Alert origin. Default is `"InfluxDB"`.
```suggestion
// - url: Alerta URL.
// - apiKey: Alerta API key.
// - environment: Alert environment. Default is `""`.
//
//   **Valid values**:
//   - `"Production"`
//   - `"Development"`
//   - empty string (`""`) _(default)_.
//
// - origin: Alert origin. Default is `"InfluxDB"`.
```

2021-11-10 21:08 UTC, sanderson commented on stdlib/contrib/bonitoo-io/alerta/alerta.flux
> +//     The output function requires a `mapFn` parameter.
```suggestion
// `alerta.endpoint` is a factory function that outputs another function.
// The output function requires a `mapFn` parameter.
```

2021-11-11 15:36 UTC, sanderson approved these changes

2021-11-11 16:21 UTC, merged