feat(docs): document `hex` package
influxdata/flux pull request #4235
Opened 2021-11-08 17:15 UTC by pierwill

2021-11-08 17:32 UTC, sanderson requested changes
We need to port all the **examples** and **tags** from the [hex package docs](https://docs.influxdata.com/flux/v0.x/stdlib/contrib/bonitoo-io/hex/).

2021-11-08 17:32 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +// - v: string to convert.
```suggestion
// - v: String to convert.
```

2021-11-08 17:32 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +// - v: string to convert.
```suggestion
// - v: String to convert.
```

2021-11-08 17:32 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +// of `int`, `uint` or `bytes` values to and from `string` values.
```suggestion
// of `int`, `uint` or `bytes` values to and from `string` values.
//
// introduced: 0.131.0
```

2021-11-08 17:32 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +// string converts an integer string to a hexadecimal string.
```suggestion
// string converts a Flux basic type to a hexadecimal string.
//
// The function is similar to `string()`, but encodes int, uint, and bytes
// types to hexadecimal lowercase characters.
```

2021-11-08 17:40 UTC, pierwill commented
Bad git happening here...

2021-11-08 17:42 UTC, pierwill commented
Still need to port examples.

2021-11-08 17:55 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +//
Each example needs an h3 title.

2021-11-08 17:57 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +//
This function in particular has many examples: https://docs.influxdata.com/flux/v0.x/stdlib/contrib/bonitoo-io/hex/string/#examples

2021-11-08 21:14 UTC, nathanielc requested changes

2021-11-08 21:14 UTC, nathanielc commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +// tag: type-conversion
these tags and other metadata must be the last lines of the comment or they will not be parsed.

2021-11-08 21:14 UTC, nathanielc commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +// Returns [255 87 51] (bytes)
nit, missing extra `//`

2021-11-09 20:01 UTC, nathanielc approved these changes

2021-11-10 00:03 UTC, sanderson requested changes

2021-11-10 00:03 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +// ### Convert a duration to a hexadecimal string value
~~~suggestion
// ```
//
// ### Convert a duration to a hexadecimal string value
~~~

2021-11-10 00:03 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +// ### Convert a float to a hexadecimal string value
~~~suggestion
// ```
//
// ### Convert a float to a hexadecimal string value
~~~

2021-11-10 00:03 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +// ### Convert bytes to a hexadecimal string value
~~~suggestion
// ```
//
// ### Convert bytes to a hexadecimal string value
~~~

2021-11-10 00:03 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +//
~~~suggestion
// // Returns "48656c6c6f20776f726c6421"
// ```
// 
~~~

2021-11-10 00:03 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +// The following example uses data provided by the sampledata package.
```suggestion
// Use `map()` to iterate over and update all input rows.
// Use `hex.string()` to update the value of a column.
// The following example uses data provided by the sampledata package.
```

2021-11-10 00:03 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +//   |> map(fn:(r) => ({ r with _value: hex.string(v: r.foo) }))
```suggestion
// < data
// >     |> map(fn:(r) => ({ r with _value: hex.string(v: r.foo) }))
```

2021-11-10 00:03 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +//   |> map(fn: (r) => ({ r with _value: r._value * 1000 }))
```suggestion
//     |> map(fn: (r) => ({ r with _value: r._value * 1000 }))
```

2021-11-10 00:03 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +// ### Convert hexadecimal string to unsigned integer
```suggestion
// ### Convert a hexadecimal string to an unsigned integer
```

2021-11-10 00:03 UTC, sanderson commented on stdlib/contrib/bonitoo-io/hex/hex.flux
> +// ### Convert string into bytes
```suggestion
// ### Convert a hexadecimal string into bytes
```

2021-11-10 17:25 UTC, sanderson approved these changes

2021-11-10 17:37 UTC, merged