feat(docs): document `servicenow` package
influxdata/flux pull request #4236
Opened 2021-11-08 17:51 UTC by pierwill

2021-11-10 00:10 UTC, sanderson requested changes

2021-11-10 00:10 UTC, sanderson commented on stdlib/contrib/bonitoo-io/servicenow/servicenow.flux
> +//   Supported values:
```suggestion
//
//   Supported values:
//
```

2021-11-10 00:10 UTC, sanderson commented on stdlib/contrib/bonitoo-io/servicenow/servicenow.flux
> +// )
`flux fmt`'d

```suggestion
import "contrib/bonitoo-io/servicenow"
import "influxdata/influxdb/secrets"

username = secrets.get(key: "SERVICENOW_USERNAME")
password = secrets.get(key: "SERVICENOW_PASSWORD")

lastReported = from(bucket: "example-bucket")
    |> range(start: -1m)
    |> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_idle")
    |> last()
    |> findRecord(fn: (key) => true, idx: 0)

servicenow.event(
    url: "https://tenant.service-now.com/api/global/em/jsonv2",
    username: username,
    password: password,
    node: lastReported.host,
    metricType: lastReported._measurement,
    resource: lastReported.instance,
    metricName: lastReported._field,
    severity: if lastReported._value < 1.0 then
        "critical"
    else if lastReported._value < 5.0 then
        "warning"
    else
        "info",
    additionalInfo: {"devId": r.dev_id},
)
```

2021-11-10 00:10 UTC, sanderson commented on stdlib/contrib/bonitoo-io/servicenow/servicenow.flux
>  // ```
~~~suggestion
// ```
//
// tags: single notification
//
~~~

2021-11-10 00:10 UTC, sanderson commented on stdlib/contrib/bonitoo-io/servicenow/servicenow.flux
> +// - password: (Required) ServiceNow password to use for HTTP BASIC authentication.
The "required" tags aren't needed. If a parameter is required, that metadata is included in the generated fluxdoc JSON and we can dynamically apply styles using that metadata.

```suggestion
// - url: ServiceNow web service URL.
// - username: ServiceNow username to use for HTTP BASIC authentication.
// - password: ServiceNow password to use for HTTP BASIC authentication.
```

2021-11-10 00:10 UTC, sanderson commented on stdlib/contrib/bonitoo-io/servicenow/servicenow.flux
> +// ## Usage:
```suggestion
// ## Usage
```

2021-11-10 00:10 UTC, sanderson commented on stdlib/contrib/bonitoo-io/servicenow/servicenow.flux
> +// (For more information, see `servicenow.event()` parameters.)
```suggestion
// For more information, see `servicenow.event()` parameters.
```

2021-11-10 00:10 UTC, sanderson commented on stdlib/contrib/bonitoo-io/servicenow/servicenow.flux
>  // ```
```suggestion
// ```
//
// tags: notification endpoints
//
```

2021-11-10 00:10 UTC, sanderson commented on stdlib/contrib/bonitoo-io/servicenow/servicenow.flux
> +// - severity: (Required) Severity of the event.
```suggestion
// - url: ServiceNow web service URL.
// - username: ServiceNow username to use for HTTP BASIC authentication.
// - password: ServiceNow password to use for HTTP BASIC authentication.
// - description: Event description.
// - severity: Severity of the event.
```

2021-11-10 18:00 UTC, nathanielc approved these changes
Looks good after a few small changes, no need for another review.

2021-11-10 18:00 UTC, nathanielc commented on stdlib/contrib/bonitoo-io/servicenow/servicenow.flux
> +//
same

2021-11-10 23:23 UTC, pierwill commented on stdlib/contrib/bonitoo-io/servicenow/servicenow.flux
> +//
```suggestion
// tags: notification endpoints
```

2021-11-10 23:23 UTC, pierwill commented on stdlib/contrib/bonitoo-io/servicenow/servicenow.flux
> +//
```suggestion
// tags: single notification
```

2021-11-11 15:38 UTC, sanderson approved these changes

2021-11-11 15:38 UTC, sanderson commented on stdlib/contrib/bonitoo-io/servicenow/servicenow.flux
> +// Package servicenow  provides functions for sending events to ServiceNow.
```suggestion
// Package servicenow  provides functions for sending events to [ServiceNow](https://www.servicenow.com/).
```

2021-11-11 16:51 UTC, merged