feat(docs): document `tickscript` package
influxdata/flux pull request #4237
Opened 2021-11-08 20:43 UTC by pierwill

2021-11-10 22:38 UTC, sanderson requested changes

2021-11-10 22:38 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +// ```
```suggestion
// selectWindow changes a column’s name, windows rows by time, and then applies an
// aggregate or selector function the specified column for each window of time.
//
// ## TICKscript helper function
// `tickscript.selectWindow` is a helper function meant to replicate TICKscript operations like the following:
//
// ```
// // Rename, window, and aggregate
// query("SELECT f(x) AS y")
//   .groupBy(time(t), ...)
// ```
```

2021-11-10 22:38 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +//   Must be the same data type as column.
```suggestion
// - column: Column to operate on. Default is _value.
// - fn: Aggregate or selector function to apply.
// - as: New column name.
// - every: Duration of windows.
// - defaultValue: Default fill value for null values in column.
//   Must be the same data type as column.
// - tables: Input data. Default is piped-forward data (`<-`).
```

2021-11-10 22:38 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +//   )
```suggestion
// import "contrib/bonitoo-io/tickscript"
// # import "sampledata"
// # 
// # data = sampledata.int()
// #    |> range(start: sampledata.start, stop: sampledata.stop)
// 
// < data
//     |> tickscript.selectWindow(
//         fn: sum,
//         as: "example-name",
//         every: 1h,
//         defaultValue: 0,
// >     )
```

2021-11-10 22:38 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +// function.
```suggestion
// compute is an alias for `tickscript.select()` that changes a column’s name and
// optionally applies an aggregate or selector function.
```

2021-11-10 22:38 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +//   function to apply.
```suggestion
// - as: New column name.
// - column: Column to operate on. Default is `_value`.
// - fn: Aggregate or selector function to apply.
// - tables: Input data. Default is piped-forward data (`<-`).
//
// tags: transformations
```

2021-11-10 22:38 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +// This function is comparable to [Kapacitor QueryNode .groupBy](https://docs.influxdata.com/kapacitor/v1.6/nodes/query_node/#groupby).
```suggestion
// This function is comparable to [Kapacitor QueryNode .groupBy](https://docs.influxdata.com/kapacitor/latest/nodes/query_node/#groupby).
```

2021-11-10 22:38 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +// (To group by intervals of time, use `window()` or `tickscript.selectWindow()`.)
```suggestion
// **Note**: To group by time intervals, use `window()` or `tickscript.selectWindow()`.
```

2021-11-10 22:38 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +//
```suggestion
// ## Parameters
// - columns: List of columns to group by.
// - tables: Input data. Default is piped-forward data (`<-`).
//
```

2021-11-10 22:38 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +// ```
```suggestion
// ### Group by host and region
// ```
// # import "array"
// import "contrib/bonitoo-io/tickscript"
// 
// # data = array.from(
// #     rows: [
// #         {_time: 2021-01-01T00:00:00Z, _measurement: "m", host: "h1", region: "east", _field: "foo", _value: 1.2},
// #         {_time: 2021-01-01T00:01:00Z, _measurement: "m", host: "h1", region: "east", _field: "foo", _value: 3.4},
// #         {_time: 2021-01-01T00:00:00Z, _measurement: "m", host: "h2", region: "east", _field: "foo", _value: 2.3},
// #         {_time: 2021-01-01T00:01:00Z, _measurement: "m", host: "h2", region: "east", _field: "foo", _value: 5.6},
// #         {_time: 2021-01-01T00:00:00Z, _measurement: "m", host: "h3", region: "west", _field: "foo", _value: 1.2},
// #         {_time: 2021-01-01T00:01:00Z, _measurement: "m", host: "h3", region: "west", _field: "foo", _value: 3.4},
// #         {_time: 2021-01-01T00:00:00Z, _measurement: "m", host: "h4", region: "west", _field: "foo", _value: 2.3},
// #         {_time: 2021-01-01T00:01:00Z, _measurement: "m", host: "h4", region: "west", _field: "foo", _value: 5.6},
// #     ],
// # )
// # 
// < data
// >     |> tickscript.groupBy(columns: ["host", "region"])
// ```
//
// tags: transformations
```

2021-11-10 22:38 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +// This function is comparable to [Kapacitor JoinNode](https://docs.influxdata.com/kapacitor/v1.6/nodes/join_node/).
```suggestion
// This function is comparable to [Kapacitor JoinNode](https://docs.influxdata.com/kapacitor/latest/nodes/join_node/).
```

2021-11-10 22:38 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +// - measurement: - string -(Required) Measurement name to use in results.
```suggestion
// - tables: Map of two streams to join.
// - on: List of columns to join on. Default is `["_time"]`.
// - measurement: Measurement name to use in results.
```

2021-11-10 22:38 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +// [OUTPUT DATA]
```suggestion
// ```
// import "array"
// import "contrib/bonitoo-io/tickscript"
// 
// metrics = array.from(
//     rows: [
//         {_time: 2021-01-01T00:00:00Z, host: "host1", _value: 1.2},
//         {_time: 2021-01-01T01:00:00Z, host: "host1", _value: 0.8},
//         {_time: 2021-01-01T02:00:00Z, host: "host1", _value: 3.2},
//         {_time: 2021-01-01T00:00:00Z, host: "host2", _value: 8.4},
//         {_time: 2021-01-01T01:00:00Z, host: "host2", _value: 7.3},
//         {_time: 2021-01-01T02:00:00Z, host: "host2", _value: 7.9},
//     ],
// )
//     |> group(columns: ["host"])
// 
// states = array.from(
//     rows: [
//         {_time: 2021-01-01T00:00:00Z, host: "host1", _value: "dead"},
//         {_time: 2021-01-01T01:00:00Z, host: "host1", _value: "dead"},
//         {_time: 2021-01-01T02:00:00Z, host: "host1", _value: "alive"},
//         {_time: 2021-01-01T00:00:00Z, host: "host2", _value: "alive"},
//         {_time: 2021-01-01T01:00:00Z, host: "host2", _value: "alive"},
//         {_time: 2021-01-01T02:00:00Z, host: "host2", _value: "alive"},
//     ],
// )
//     |> group(columns: ["host"])
// 
// tickscript.join(
//     tables: {metric: metrics, state: states},
//     on: ["_time", "host"],
//     measurement: "example-m",
// > )
//```
//
// tags: transformations
```

2021-11-11 13:43 UTC, scbrickley approved these changes

2021-11-11 16:08 UTC, sanderson approved these changes
Two suggestions and then it's good to go.

2021-11-11 16:08 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +// ```
```suggestion
// ```no_run
```

2021-11-11 16:08 UTC, sanderson commented on stdlib/contrib/bonitoo-io/tickscript/tickscript.flux
> +// - columns: (Required) List of columns to group by.
```suggestion
// - columns: List of columns to group by.
```

2021-11-11 17:32 UTC, merged