feat(docs): document `teams` package
influxdata/flux pull request #4249
Opened 2021-11-09 21:48 UTC by pierwill

2021-11-10 05:23 UTC, sanderson requested changes

2021-11-10 05:23 UTC, sanderson commented on stdlib/contrib/sranka/teams/teams.flux
> +// [incoming webhook]: https://docs.microsoft.com/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook
```suggestion
// message sends a single message to a Microsoft Teams channel using an
// [incoming webhook](https://docs.microsoft.com/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook).
```

2021-11-10 05:23 UTC, sanderson commented on stdlib/contrib/sranka/teams/teams.flux
> +//   If no summary is provided, Flux generates the summary from the message text.
```suggestion
// - summary: Message card summary.
//   Default is `""`.
//
//   If no summary is provided, Flux generates the summary from the message text.
```

2021-11-10 05:23 UTC, sanderson commented on stdlib/contrib/sranka/teams/teams.flux
> +// )
```suggestion
// import "contrib/sranka/teams"
// 
// lastReported = from(bucket: "example-bucket")
//     |> range(start: -1m)
//     |> filter(fn: (r) => r._measurement == "statuses")
//     |> last()
//     |> findRecord(fn: (key) => true, idx: 0)
// 
// teams.message(
//     url: "https://outlook.office.com/webhook/example-webhook",
//     title: "Disk Usage",
//     text: "Disk usage is: *${lastReported.status}*.",
//     summary: "Disk usage is ${lastReported.status}",
// )
```

2021-11-10 05:23 UTC, sanderson commented on stdlib/contrib/sranka/teams/teams.flux
> +// ```
```suggestion
// ```
//
// tags: single notification
//
```

2021-11-10 05:23 UTC, sanderson commented on stdlib/contrib/sranka/teams/teams.flux
> +// - url: Incoming webhook URL.
```suggestion
// - url: Incoming webhook URL.
// - tables: Input data. Default is piped-forward data (`<-`).
```

2021-11-10 05:23 UTC, sanderson commented on stdlib/contrib/sranka/teams/teams.flux
> +//   )()
```suggestion
// import "contrib/sranka/teams"
//
// url = "https://outlook.office.com/webhook/example-webhook"
// endpoint = teams.endpoint(url: url)
//
// crit_statuses = from(bucket: "example-bucket")
//     |> range(start: -1m)
//     |> filter(fn: (r) => r._measurement == "statuses" and status == "crit")
//
// crit_statuses
//     |> endpoint(
//         mapFn: (r) => ({
//             title: "Disk Usage",
//             text: "Disk usage is: **${r.status}**.",
//             summary: "Disk usage is ${r.status}",
//         }),
//     )()
```

2021-11-10 05:23 UTC, sanderson commented on stdlib/contrib/sranka/teams/teams.flux
> +// ```
```suggestion
// ```
//
// tags: notification endpoints,transformations
//
```

2021-11-10 20:50 UTC, sanderson approved these changes
Suggestion to remove `tables` from `endpoint` and then it's gtg.

2021-11-10 20:50 UTC, sanderson commented on stdlib/contrib/sranka/teams/teams.flux
> +// - tables: Input data. Default is piped-forward data (`<-`).
```suggestion
```

2021-11-12 21:13 UTC, jsternberg approved these changes

2021-11-12 23:44 UTC, merged