feat(docs): document `discord` package
influxdata/flux pull request #4250
Opened 2021-11-09 22:06 UTC by pierwill

2021-11-10 05:29 UTC, sanderson requested changes

2021-11-10 05:29 UTC, sanderson commented on stdlib/contrib/chobbs/discord/discord.flux
> +// )
```suggestion
// import "contrib/chobbs/discord"
// import "influxdata/influxdb/secrets"
// 
// token = secrets.get(key: "DISCORD_TOKEN")
// 
// lastReported = from(bucket: "example-bucket")
//     |> range(start: -1m)
//     |> filter(fn: (r) => r._measurement == "statuses")
//     |> last()
//     |> findRecord(fn: (key) => true, idx: 0)
// 
// discord.send(
//     webhookToken: token,
//     webhookID: "1234567890",
//     username: "chobbs",
//     content: "The current status is \"${lastReported.status}\".",
//     avatar_url: "https://staff-photos.net/pic.jpg",
// )
```

2021-11-10 05:29 UTC, sanderson commented on stdlib/contrib/chobbs/discord/discord.flux
> +// ```
```suggestion
// ```
//
// tags: single notification
//
```

2021-11-10 05:29 UTC, sanderson commented on stdlib/contrib/chobbs/discord/discord.flux
> +// [Discord webhook]: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks&?page=3
```suggestion
// endpoint sends a single message to a Discord channel using a
// [Discord webhook](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks&?page=3)
// and data from table rows.
```

2021-11-10 05:29 UTC, sanderson commented on stdlib/contrib/chobbs/discord/discord.flux
> +//
```suggestion
// - avatar_url: Override the Discord webhook’s default avatar.
// - tables: Input data. Default is piped-forward data (`<-`).
```

2021-11-10 05:29 UTC, sanderson commented on stdlib/contrib/chobbs/discord/discord.flux
> +//   )()
```suggestion
// import "influxdata/influxdb/secrets"
// import "contrib/chobbs/discord"
// 
// discordToken = secrets.get(key: "DISCORD_TOKEN")
// endpoint = telegram.endpoint(
//     webhookToken: discordToken,
//     webhookID: "123456789",
//     username: "critBot",
// )
// 
// crit_statuses = from(bucket: "example-bucket")
//     |> range(start: -1m)
//     |> filter(fn: (r) => r._measurement == "statuses" and status == "crit")
// 
// crit_statuses
//     |> endpoint(
//         mapFn: (r) => ({
//             content: "The status is critical!",
//         }),
//     )()
```

2021-11-10 05:29 UTC, sanderson commented on stdlib/contrib/chobbs/discord/discord.flux
> +// ```
```suggestion
// ```
//
// tags: notifcation endpoints,transformations
//
```

2021-11-10 16:22 UTC, sanderson approved these changes
One nit, and it's gtg.

2021-11-10 16:22 UTC, sanderson commented on stdlib/contrib/chobbs/discord/discord.flux
> +// ## Usage
```suggestion
//
// ## Usage
```

2021-11-11 06:25 UTC, skartikey approved these changes

2021-11-11 17:59 UTC, merged