feat(docs): document `events` package
influxdata/flux pull request #4251
Opened 2021-11-09 22:16 UTC by pierwill

2021-11-10 05:52 UTC, sanderson requested changes

2021-11-10 05:52 UTC, sanderson commented on stdlib/contrib/tomhollingworth/events/duration.flux
> +//
```suggestion
// - stop: The latest time to use when calculating results.
//
//   If provided, `stop` overrides the time value in the `stopColumn`.
//
// - tables: Input data. Default is piped-forward data (`<-`).
//
```

2021-11-10 05:52 UTC, sanderson commented on stdlib/contrib/tomhollingworth/events/duration.flux
> +//   )
```suggestion
// import "array"
// import "contrib/tomhollingworth/events"
// 
// # data = array.from(
// #     rows: [
// #         {_time: 2020-01-01T00:00:00Z, state: "ok"},
// #         {_time: 2020-01-01T00:12:34Z, state: "warn"},
// #         {_time: 2020-01-01T00:25:01Z, state: "ok"},
// #         {_time: 2020-01-01T16:07:55Z, state: "crit"},
// #         {_time: 2020-01-01T16:54:21Z, state: "warn"},
// #         {_time: 2020-01-01T18:20:45Z, state: "ok"},
// #     ],
// # )
// #
// < data
//     |> events.duration(
//         unit: 1m,
//         stop: 2020-01-02T00:00:00Z,
// >     )
```

2021-11-10 05:52 UTC, sanderson commented on stdlib/contrib/tomhollingworth/events/duration.flux
> +// [OUTPUT]
~~~suggestion
// ### Compared to similar functions
//
// The example below includes output values of
// `events.duration()`, `elapsed()`, and `stateDuration()`
// related to the `_time` and `state` values of input data.
//
// ```
// import "array"
// import "contrib/tomhollingworth/events"
//
// # data = array.from(
// #     rows: [
// #         {_time: 2020-01-01T00:00:00Z, state: "ok"},
// #         {_time: 2020-01-01T00:12:34Z, state: "warn"},
// #         {_time: 2020-01-01T00:25:01Z, state: "ok"},
// #         {_time: 2020-01-01T16:07:55Z, state: "crit"},
// #         {_time: 2020-01-01T16:54:21Z, state: "warn"},
// #         {_time: 2020-01-01T18:20:45Z, state: "ok"},
// #     ],
// # )
// #
// union(
//     tables: [
//         data |> events.duration(unit: 1m, stop: 2020-01-02T00:00:00Z) |> map(fn: (r) => ({_time: r._time, state: r.state, function: "events.Duration()", value: r.duration})),
//         data |> elapsed(unit: 1m) |> map(fn: (r) => ({_time: r._time, state: r.state, function: "elapsed()", value: r.elapsed})),
//         data |> stateDuration(unit: 1m, fn: (r) => true) |> map(fn: (r) => ({_time: r._time, state: r.state, function: "stateDuration()", value: r.stateDuration})),
//     ],
// )
// >     |> pivot(rowKey: ["_time", "state"], columnKey: ["function"], valueColumn: "value")
// ```
//
// tags: transformations,events
//
~~~

2021-11-10 16:20 UTC, sanderson approved these changes
Two suggestions and it's gtg.

2021-11-10 16:20 UTC, sanderson commented on stdlib/contrib/tomhollingworth/events/duration.flux
> +// >For examples, see below.
- This stuff will just get dropped into the JSON output as raw markdown, so we need to format code as code.
- We won't be using blockquote styling for notes in the generated docs.

```suggestion
// ### Similar functions
// `events.duration()` is similar to `elapsed()` and `stateDuration()`, but differs in important ways:
// 
// - `elapsed()` drops the first record. `events.duration()` does not.
// - `stateDuration()` calculates the total time spent in a state (determined by a predicate function).
//   `events.duration()` returns the duration between all records and their subsequent records.
// 
// See the example [below](#compared-to-similar-functions).
```

2021-11-10 16:20 UTC, sanderson commented on stdlib/contrib/tomhollingworth/events/duration.flux
> +// to the timestamp in the stopColumn or the specified stop time.
```suggestion
// to the timestamp in the `stopColumn` or the specified stop time.
```

2021-11-11 18:46 UTC, jsternberg approved these changes
Just needs a rebase and to regenerate files.

2021-11-11 19:30 UTC, merged