[WIP]: first prototype of cumulative reduce. functionality is there, but no …
influxdata/flux pull request #4387
Opened 2022-01-04 21:56 UTC by aanthony1243

…params to change back to regular mode

### Done checklist
- [ ] docs/SPEC.md updated
- [ ] Test cases written

2022-01-04 22:41 UTC, sanderson commented
To toggle this added functionality and output all rows from the reduce operation, we should add a new boolean parameter `emitAll` (or `outputAll` _(never a new feature without some bike-shedding 😄)_).

With `emitAll: true`, output tables include rows for each corresponding input row. The default value is `false` to preserve backwards compatibility with the existing `reduce` behavior.

2022-01-05 02:34 UTC, aanthony1243 commented
I don't have a strong opinion on the parameter name, i'm not sure if there's precedent in another function that has a similar option, @sanderson maybe you have some idea if that's possibly true?

2022-01-05 03:22 UTC, aanthony1243 commented
pushed a new version, this is the current behavior: 

```
import "sampledata"

stateChangeTest = (tables=<-, c) => tables
  |> reduce(identity: {prev: 0, current: 0, different: false}, fn: (r, accumulator) => ({ prev: accumulator.current, current: r._value, different: accumulator.current != r._value }), cumulative:c)

sampledata.int() |> stateChangeTest(c: false) |> yield(name: "legacy")
sampledata.int() |> stateChangeTest(c: true) |> yield(name: "cumulative")

----------------------------------
Result: legacy
Table: keys: [tag]
            tag:string                 current:int  different:bool                    prev:int
----------------------  --------------------------  --------------  --------------------------
                    t1                           4            true                          15
Table: keys: [tag]
            tag:string                 current:int  different:bool                    prev:int
----------------------  --------------------------  --------------  --------------------------
                    t2                           1            true                          13
Result: cumulative
Table: keys: [tag]
            tag:string                 current:int  different:bool                    prev:int
----------------------  --------------------------  --------------  --------------------------
                    t1                          -2            true                           0
                    t1                          10            true                          -2
                    t1                           7            true                          10
                    t1                          17            true                           7
                    t1                          15            true                          17
                    t1                           4            true                          15
Table: keys: [tag]
            tag:string                 current:int  different:bool                    prev:int
----------------------  --------------------------  --------------  --------------------------
                    t2                          19            true                           0
                    t2                           4            true                          19
                    t2                          -3            true                           4
                    t2                          19            true                          -3
                    t2                          13            true                          19
                    t2                           1            true                          13
```

2022-01-05 19:48 UTC, sanderson commented
@aanthony1243 I don't have a strong opinion either about the parameter name, although I don't know that `cumulative` is the right one. Cumulative calculations are a use case, but I don't think they are _the_ use case. I think `emitAll` or `emitEach` would work.

2022-01-05 19:59 UTC, aanthony1243 commented
I will go with emitAll

2022-01-06 08:44 UTC, lazarenkovegor commented
really looking forward to this feature. Can you tell me if it is possible to collect this feature before it appears in the release? Or is there an instruction on how to build and test your own function in golang? I found only instructions on where to push my functions, but I did not find instructions on how to raise the test environment locally.

2022-01-06 18:38 UTC, aanthony1243 commented
@lazarenkovegor it's possible to build+test this branch, instructions are in the README.  After you can build flux standalone, linking it into and building influxdb is a straightforward redirect of the go.mod dependency to the local flux directory.

2022-01-08 21:03 UTC, geropl commented
I happened to find this PR from this discussion: https://github.com/influxdata/flux/issues/2452#issuecomment-1007382967

Really looking forward for this to get merged, thx for working on it! :pray: 

FYI here's a slightly different (more bulky?) approach to the problem: https://github.com/influxdata/flux/pull/4395
Sharing here in case it might help learn about the design space. :+1:

2022-01-10 11:20 UTC, Marwes requested changes

2022-01-10 11:20 UTC, Marwes commented on stdlib/universe/reduce.go
> +			key := t.computeGroupKey(tbl.Key(), m)
This seems entirely duplicated from the same code below. Should factor it out to a function if it does not make sense to keep it in the loop (as the added comment mentions).

2023-07-12 01:59 UTC, closed without merging