chore(docs): Add downsampling example for isType
influxdata/flux pull request #4523
Opened 2022-03-02 17:32 UTC by pierwill

### Done checklist
- [ ] docs/SPEC.md updated
- [ ] Test cases written

2022-03-02 17:32 UTC, jsternberg approved these changes

2022-03-02 18:10 UTC, sanderson requested changes
When possible, the examples in the inline docs need to be executable without external dependencies. The suggestions I made allow for that. Also, I added an example for aggregating/selecting by type as well as downgrading.

2022-03-02 18:10 UTC, sanderson commented on stdlib/types/types.flux
> +// ### Downsampling data based on type
~~~suggestion
// ### Aggregate or select data based on type
// ```
// # import "csv"
// import "types"
// # 
// # csvData = "
// # #group,false,false,false,true,false
// # #datatype,string,long,dateTime:RFC3339,string,double
// # #default,_result,,,,
// # ,result,table,_time,type,_value
// # ,,0,2021-01-01T00:00:00Z,float,-2.18
// # ,,0,2021-01-01T00:00:10Z,float,10.92
// # ,,0,2021-01-01T00:00:20Z,float,7.35
// # 
// # #group,false,false,false,true,false
// # #datatype,string,long,dateTime:RFC3339,string,boolean
// # #default,_result,,,,
// # ,result,table,_time,type,_value
// # ,,0,2021-01-01T00:00:00Z,bool,true
// # ,,0,2021-01-01T00:00:10Z,bool,true
// # ,,0,2021-01-01T00:00:20Z,bool,false
// # 
// # #group,false,false,false,true,false
// # #datatype,string,long,dateTime:RFC3339,string,string
// # #default,_result,,,,
// # ,result,table,_time,type,_value
// # ,,0,2021-01-01T00:00:00Z,string,smpl_g9qczs
// # ,,0,2021-01-01T00:00:10Z,string,smpl_0mgv9n
// # ,,0,2021-01-01T00:00:20Z,string,smpl_phw664
// # 
// # #group,false,false,false,false,true
// # #datatype,string,long,dateTime:RFC3339,long,string
// # #default,_result,,,,
// # ,result,table,_time,_value,type
// # ,,0,2021-01-01T00:00:00Z,-2,int
// # ,,0,2021-01-01T00:00:10Z,10,int
// # ,,0,2021-01-01T00:00:20Z,7,int
// # "
// # 
// # data = csv.from(csv: csvData)
//
// < nonNumericData = data
//     |> filter(fn: (r) => types.isType(v: r._value, type: "string") or types.isType(v: r._value, type: "bool"))
//     |> last()
//
// numericData = data
//     |> filter(fn: (r) => types.isType(v: r._value, type: "int") or types.isType(v: r._value, type: "float"))
//     |> mean()
//
// > union(tables: [nonNumericData, numericData])
// ```
//
// ### Downsample data based on type
~~~

2022-03-02 18:10 UTC, sanderson commented on stdlib/types/types.flux
> +// ```
~~~suggestion
// ```
// # import "csv"
// # import "sampledata"
// import "types"
// # 
// # data = csv.from(
// #     csv: "
// # #group,false,false,false,true,false
// # #datatype,string,long,dateTime:RFC3339,string,double
// # #default,_result,,,,
// # ,result,table,_time,type,_value
// # ,,0,2021-01-01T00:00:00Z,float,-2.18
// # ,,0,2021-01-01T00:00:10Z,float,10.92
// # ,,0,2021-01-01T00:00:20Z,float,7.35
// # ,,0,2021-01-01T00:00:30Z,float,17.53
// # ,,0,2021-01-01T00:00:40Z,float,15.23
// # ,,0,2021-01-01T00:00:50Z,float,4.43
// # 
// # #group,false,false,false,true,false
// # #datatype,string,long,dateTime:RFC3339,string,boolean
// # #default,_result,,,,
// # ,result,table,_time,type,_value
// # ,,0,2021-01-01T00:00:00Z,bool,true
// # ,,0,2021-01-01T00:00:10Z,bool,true
// # ,,0,2021-01-01T00:00:20Z,bool,false
// # ,,0,2021-01-01T00:00:30Z,bool,true
// # ,,0,2021-01-01T00:00:40Z,bool,false
// # ,,0,2021-01-01T00:00:50Z,bool,false
// # 
// # #group,false,false,false,true,false
// # #datatype,string,long,dateTime:RFC3339,string,string
// # #default,_result,,,,
// # ,result,table,_time,type,_value
// # ,,0,2021-01-01T00:00:00Z,string,smpl_g9qczs
// # ,,0,2021-01-01T00:00:10Z,string,smpl_0mgv9n
// # ,,0,2021-01-01T00:00:20Z,string,smpl_phw664
// # ,,0,2021-01-01T00:00:30Z,string,smpl_guvzy4
// # ,,0,2021-01-01T00:00:40Z,string,smpl_5v3cce
// # ,,0,2021-01-01T00:00:50Z,string,smpl_s9fmgy
// # 
// # #group,false,false,false,false,true
// # #datatype,string,long,dateTime:RFC3339,long,string
// # #default,_result,,,,
// # ,result,table,_time,_value,type
// # ,,0,2021-01-01T00:00:00Z,-2,int
// # ,,0,2021-01-01T00:00:10Z,10,int
// # ,,0,2021-01-01T00:00:20Z,7,int
// # ,,0,2021-01-01T00:00:30Z,17,int
// # ,,0,2021-01-01T00:00:40Z,15,int
// # ,,0,2021-01-01T00:00:50Z,4,int
// # ",
// # )
// #     |> range(start: sampledata.start, stop: sampledata.stop)
// 
// < nonNumericData = data
//     |> filter(fn: (r) => types.isType(v: r._value, type: "string") or types.isType(v: r._value, type: "bool"))
//     |> aggregateWindow(every: 30s, fn: last)
// 
// numericData = data
//     |> filter(fn: (r) => types.isType(v: r._value, type: "int") or types.isType(v: r._value, type: "float"))
//     |> aggregateWindow(every: 30s, fn: mean)
// 
// > union(tables: [nonNumericData, numericData])
// ```
~~~

2022-03-04 18:08 UTC, sanderson approved these changes

2022-03-04 18:09 UTC, merged