chore(fluxdocs): add docs for internal and misc pacakges
influxdata/flux pull request #4546
Opened 2022-03-09 22:58 UTC by nathanielc

There were several packages we had not yet documented because they were
for testing or internal use only. This PR adds docs to those packages so
that they pass the linter checks.

### Done checklist
- [ ] docs/SPEC.md updated
- [ ] Test cases written

2022-03-09 23:32 UTC, sanderson requested changes
Suggestions for punctuation, formatting, and verbiage changes.

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/debug/debug.flux
> +// - tables: Stream to discard
```suggestion
// - tables: Stream to discard.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/debug/debug.flux
> +// - name: Name of the option
```suggestion
// getOption gets the value of an option using a form of reflection.
//
// ## Parameters
// - pkg: Full path of the package.
// - name: Option name.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/debug/debug.flux
> +// - key: Name of the feature flag
```suggestion
// - key: Feature flag name.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/gen/gen.flux
> +// tables generates a stream of table data
```suggestion
// tables generates a stream of table data.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/gen/gen.flux
> +// - tags: Set of tags with their cardinality that should be generated.
```suggestion
// - nulls: Percentage chance that a null value will be used in the input. Valid value range is `[0.0 - 1.0]`.
// - tags: Set of tags with their cardinality to generate.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/influxql/influxql.flux
> +// Package influxql provides some constants
```suggestion
// Package influxql provides constants for working with InfluxQL.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/influxql/influxql.flux
> +// maxTime is the latest time InfluxQL can represent
```suggestion
// minTime is the earliest time InfluxQL can represent.
minTime = 1677-09-21T00:12:43.145224194Z

// maxTime is the latest time InfluxQL can represent.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#changes
```suggestion
// changes implements functionality equivalent to
// [PromQL's `changes()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#changes).
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
> +// - tables: Stream of tables.
```suggestion
// - tables: Input data. Default is piped-forward data (`<-`).
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#day_of_month
```suggestion
// promqlDayOfMonth implements functionality equivalent to 
// [PromQL's `day_of_month()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#day_of_month).
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#day_of_week
```suggestion
// promqlDayOfWeek implements functionality equivalent to
// [PromQL's `day_of_week()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#day_of_week).
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#days_in_month
```suggestion
// promqlDaysInMonth implements functionality equivalent to
// [PromQL's `days_in_month()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#days_in_month).
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#vector
```suggestion
// emptyTable returns an empty table, which is used as a helper function to implement
// PromQL's [`time()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#time) and
// [`vector()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#vector) functions.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#delta
```suggestion
// extrapolatedRate is a helper function that calculates extrapolated rates over
// counters and is used to implement PromQL's
// [`rate()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate),
// [`delta()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase),
// and [`increase()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#delta) functions.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
> +// - isRate: True if the data represents a rate
```suggestion
// ## Parameters
// - tables: Input data. Default is piped-forward data (`<-`).
// - isCounter: Data represents a counter.
// - isRate: Data represents a rate.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#holt_winters
```suggestion
// holtWinters implements functionality equivalent to
// [PromQL's `holt_winters()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#holt_winters).
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
> +// - trendFactor: Trend factor
```suggestion
// - tables: Input data. Default is piped-forward data (`<-`).
// - smoothingFactor: Exponential smoothing factor.
// - trendFactor: Trend factor.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#hour
```suggestion
// promqlHour implements functionality equivalent to
// [PromQL's `hour()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#hour).
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#idelta
```suggestion
// instantRate is a helper function that calculates instant rates over
// counters and is used to implement PromQL's
// [`irate()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#irate) and
// [`idelta()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#idelta) functions.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
> +// - isRate: True if the data represents a rate
```suggestion
// - tables: Input data. Defaults is piped-forward data (`<-`).
// - isRate: Data represents a rate.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#label_replace
```suggestion
// labelReplace implements functionality equivalent to
// [PromQL's `label_replace()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#label_replace).
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
> +// - replacement: Replacement value
```suggestion
// - tables: Input data. Default is piped-forward data (`<-`).
// - source: Input label.
// - destination: Output label.
// - regex: Pattern as a regex string.
// - replacement: Replacement value.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
> +// - fromNow: Time as a floating point value
```suggestion
// - tables: Input data. Default is piped-forward data (`<-`).
// - predict: Output should contain a prediction.
// - fromNow: Time as a floating point value.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#minute
```suggestion
// promqlMinute implements functionality equivalent to
// [PromQL's `minute()` function]( https://prometheus.io/docs/prometheus/latest/querying/functions/#minute).
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#month
```suggestion
// promqlMonth implements functionality equivalent to
// [PromQL's `month()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#month). 
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile
```suggestion
// promHistogramQuantile implements functionality equivalent to
// [PromQL's `histogram_quantile()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile).
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
> +// - valueColumn: Name of output column for the value.
```suggestion
// - tables: Input data. Default is piped-forward data (`<-`).
// - quantile: Quantile to compute (`[0.0 - 1.0]`).
// - countColumn: Count column name.
// - upperBoundColumn: Upper bound column name.
// - valueColumn: Output value column name.
```

2022-03-09 23:32 UTC, sanderson commented on libflux/flux-core/src/bin/fluxdoc.rs
> -    "universe/holt_winters",
💥

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
> +// - tables: Stream of tables.
```suggestion
// resets implements functionality equivalent to
// [PromQL's `resets()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#resets).
//
// ## Parameters
// - tables: Input data. Defaults is piped-forward data (`<-`).
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
> +// - tables: Stream of tables.
```suggestion
// timestamp implements functionality equivalent to 
// [PromQL's `timestamp()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#timestamp).
//
// ## Parameters
// - tables: Input data. Defaults is piped-forward data (`<-`).
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // https://prometheus.io/docs/prometheus/latest/querying/functions/#year
```suggestion
// promqlYear implements functionality equivalent to 
// [PromQL's `year()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#year).
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
>  // column respectively. q must be a float
```suggestion
// column respectively. `q` must be a float.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/promql/promql.flux
> +// - method: Name of the quantile method to use.
```suggestion
// - tables: Input data. Default is piped-forward data (`<-`).
// - q: Quantile to compute (`[0.0 - 1.0]`).
// - method: Quantile method to use.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/testutil/testutil.flux
> +// fail causes the current script to fail
```suggestion
// fail causes the current script to fail.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/testutil/testutil.flux
> +// makeRecord is the identity function but breaks the type connection from input to output.
```suggestion
// makeRecord is the identity function, but breaks the type connection from input to output.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/internal/testutil/testutil.flux
> +// makeAny  constructs any value based on a type description as a string
```suggestion
// makeAny constructs any value based on a type description as a string.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/planner/planner.flux
> +// Package planner provides an API for interacting with the Flux engine planner
```suggestion
// Package planner provides an API for interacting with the Flux engine planner.
```

2022-03-09 23:32 UTC, sanderson commented on stdlib/testing/expect/expect.flux
> +// - rules: Mapping of rules names to expected counts
```suggestion
// - rules: Mapping of rules names to expected counts.
```

2022-03-09 23:43 UTC, sanderson approved these changes
Looks great!

2022-03-10 01:20 UTC, rockstar approved these changes

2022-03-10 15:49 UTC, merged