fix(gen/tables): passing seed to tables generator
influxdata/flux pull request #4866
Opened 2022-06-10 14:41 UTC by skartikey

Adding seed to tables generator to get the very same sequence each time(helpful in writing test)
at the moment the seed defaults to the current time, which generates a different sequence each time.

useful in https://github.com/influxdata/flux/issues/4307

### Done checklist
- [ ] docs/SPEC.md updated
- [x] Test cases written

2022-06-10 15:09 UTC, Marwes requested changes

2022-06-10 16:33 UTC, sanderson approved these changes

2022-06-10 16:45 UTC, skartikey commented on stdlib/internal/gen/tables.go
> +	Seed  int64   `json:"Seed,omitempty"`
Thanks for catching that @Marwes

2022-06-11 13:45 UTC, Marwes approved these changes

2022-06-13 09:24 UTC, merged