Join docs
influxdata/flux pull request #4903
Opened 2022-06-21 21:07 UTC by scbrickley

Adds doc comments for the new join package, introduced in #4690

2022-06-22 14:30 UTC, nathanielc requested changes
Looks good some comments/questions below

2022-06-22 15:21 UTC, sanderson requested changes

2022-06-22 15:21 UTC, sanderson commented on stdlib/join/join.flux
> +// ## Outer Joins
```suggestion
// ## Outer joins
```

2022-06-22 15:21 UTC, sanderson commented on stdlib/join/join.flux
> +// ### Perform an Inner Join
```suggestion
// ### Perform an inner join
```

2022-06-22 15:21 UTC, sanderson commented on stdlib/join/join.flux
> +// ### Perform a Left Outer Join
```suggestion
// ### Perform a left outer join
```

2022-06-22 15:21 UTC, sanderson commented on stdlib/join/join.flux
> +// group key, you risk that value being null.
```suggestion
// In the case of a left outer join, `l` is guaranteed to not be a default record. To
// ensure that the output record has non-null values for any columns that aren't part of the group
// key, use values from `l`. Using a value from `r` that is not part of the
// risks that value being null.
```

2022-06-22 15:21 UTC, sanderson commented on stdlib/join/join.flux
> +// In this case, we should understand and expect that `v_right` will sometimes be empty.
```suggestion
// The example below constructs the output record almost entirely from properties of `l`.
// The only exception is the `v_right` column which gets its value from `r._value`.
// In this case, understand and expect that `v_right` will sometimes be null.
```

2022-06-22 15:21 UTC, sanderson commented on stdlib/join/join.flux
> +// ### Perform a Right Outer Join
```suggestion
// ### Perform a right outer join
```

2022-06-22 15:21 UTC, sanderson commented on stdlib/join/join.flux
> +// ### Perform a Full Outer Join
```suggestion
// ### Perform a full outer join
```

2022-06-22 15:21 UTC, sanderson commented on stdlib/join/join.flux
> +//   The returned record will be included in the final output.
```suggestion
//   The returned record is included in the final output.
```

2022-06-22 15:21 UTC, sanderson commented on stdlib/join/join.flux
> +//   The returned record will be included in the final output.
```suggestion
//   The returned record is included in the final output.
```

2022-06-22 15:21 UTC, sanderson commented on stdlib/join/join.flux
> +//   each chained together by the `and` operator.
```suggestion
// - on: Function that takes a left and right record (`l`, and `r` respectively), and returns a boolean.
//
//   The body of the function must be a single boolean expression, consisting of one
//   or more equality comparisons between a property of `l` and a property of `r`,
//   each chained together by the `and` operator.
```

2022-06-22 15:21 UTC, sanderson commented on stdlib/join/join.flux
> +//   each chained together by the `and` operator.
```suggestion
// - on: Function that takes a left and right record (`l`, and `r` respectively), and returns a boolean.
//
//   The body of the function must be a single boolean expression, consisting of one
//   or more equality comparisons between a property of `l` and a property of `r`,
//   each chained together by the `and` operator.
```

2022-06-22 15:21 UTC, sanderson commented on stdlib/join/join.flux
> +//   The returned record will be included in the final output.
```suggestion
//   The returned record is included in the final output.
```

2022-06-22 15:27 UTC, scbrickley commented on stdlib/join/join.flux
> +// join.tables will only compare records that have the same group key. The tables in the output will have the same grouping as the inputs.
I'm not sure I follow. Could you elaborate a bit?

2022-06-22 16:26 UTC, scbrickley commented on stdlib/universe/universe.flux
> +// deprecated: NEXT
So add the link in the `deprecated` field? As in `deprecated: NEXT, use [join.tables](url) instead`? Or somewhere else?

2022-06-22 19:11 UTC, scbrickley commented on stdlib/join/join.flux
> +//
How's this?

```
// ## Inner joins
//
// Inner joins will drop any records that don't have a match in the other input stream.
// There is no need to account for default or unmatched records when performing an inner join.
```

2022-06-22 19:20 UTC, sanderson commented on stdlib/join/join.flux
> +//
Sounds great. Only one minor change – update "will drop" to just "drop".

2022-06-22 19:24 UTC, sanderson commented on stdlib/universe/universe.flux
> +// deprecated: NEXT
No, add it to the function description. Something like this:

```
**Deprecated**: `join()` is deprecated in favor of [`join.inner()`](https://docs.influxdata.com/flux/v0.x/stdlib/join/inner/).
The [`join` package](https://docs.influxdata.com/flux/v0.x/stdlib/join/) provides support multiple join types.
```

2022-06-22 20:00 UTC, sanderson approved these changes
Just some last minute typos and then it's gtg 👍🏻

2022-06-22 20:00 UTC, sanderson commented on stdlib/join/join.flux
> +//   The body of the function must be single boolean expression, consisting of one
```suggestion
//   The body of the function must be a single boolean expression, consisting of one
```

2022-06-22 20:00 UTC, sanderson commented on stdlib/experimental/experimental.flux
> +// **Deprecated**: `experimental.join()` is deprecated in favor of [`join.inner()`](https://docs.influxdata.com/flux/v0.x/stdlib/join/inner/).
```suggestion
// **Deprecated**: `experimental.join()` is deprecated in favor of [`join.time()`](https://docs.influxdata.com/flux/v0.x/stdlib/join/time/).
```

2022-06-23 15:07 UTC, nathanielc approved these changes

2022-06-23 16:49 UTC, merged