feat: Created the headless repl file sucessfully and modified existing repl methods
influxdata/flux pull request #5040
Opened 2022-08-02 20:54 UTC by Westonside

## Description
Added in the existing code for the repl and modified existing repl methods so that the communication was done via the stdin and out. Related to : #4793 .

## Input Example

``` {"jsonrpc":"2.0","method":"Service.DidOutput","params":[{"input":"x=1"}]}```

### Checklist

Dear Author :wave:, the following checks should be completed (or explicitly dismissed) before merging.

- [x] ✏️ Write a PR description, regardless of triviality, to include the _value_ of this PR
- [x] 🔗 Reference related issues
- [x] 🏃 Test cases are included to exercise the new code
- [x] 🧪 If **new packages** are being introduced to stdlib, link to Working Group discussion notes and ensure it lands under `experimental/`
- [x] 📖 If **language features** are changing, ensure `docs/Spec.md` has been updated

Dear Reviewer(s) :wave:, you are responsible (among others) for ensuring the completeness and quality of the above before approval.

2022-08-17 17:09 UTC, Westonside commented on internal/cmd/headless_repl/main.go
> +}
Sorry, I forgot to commit the changes for these deletions so things were a little behind.

2022-08-17 17:28 UTC, Westonside commented on internal/cmd/headless_repl/main.go
> +func (r *ScopeHolder) input(t string) {
I am adding in that name  change, but the naming is the same in the current repl as well.

2022-08-17 17:38 UTC, Westonside commented on internal/cmd/headless_repl/main.go
> +func LoadQuery(q string) (string, error) {
I kept this implementation from the original repl, so I am assuming this was intended.

2022-08-26 17:37 UTC, onelson requested changes
Looks like CI is failing for `make staticcheck` which reports some unused code in here.

Once CI is passing, I think this is good to merge.

2022-08-26 19:35 UTC, onelson approved these changes
Looking good! Time to merge.

2022-08-26 19:35 UTC, merged