chore(idpe-16210): add download headers within csv dialect
influxdata/flux pull request #5328
Opened 2022-11-01 23:49 UTC by wiedld

Part of https://github.com/influxdata/idpe/issues/16210

Per feedback from the automation team (see this PR https://github.com/influxdata/idpe/pull/16212), and with approval of @nathanielc , making changes to the csv Dialect to add download headers.

### Background:
* we are doing direct filesystem download of data in the UI, bypassing browser memory.
* With this approach, the download filename is only configured with content-disposition headers.
* Made changes in queryrouterd to add the headers.
* Per automation team's request, pushing the header change into the csv Dialect.

### Checklist
- [x] ✏️ Write a PR description, regardless of triviality, to include the _value_ of this PR
- [x] 🔗 Reference related issues
- [x] 🏃 Test cases are included to exercise the new code --> test cases are in idpe.
      * the idpe test cases have already been successfully run with local changes in this package. Confirmed works.

2022-11-03 16:58 UTC, jsternberg requested changes

2022-11-03 18:29 UTC, wiedld commented on csv/dialect.go
> +		w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"influxdata_%s.csv\"; filename*=UTF-8''influxdata_%s.csv", timestamp, timestamp))
Done.

2022-11-03 19:00 UTC, nathanielc commented on csv/dialect.go
> +		w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"%s\"; filename*=UTF-8''%s", d.ResultEncoderConfig.AttachmentFilename, d.ResultEncoderConfig.AttachmentFilename))
This string construction of user supplied data makes me nervous that it will be fragile or that it will be exploitable. I would look into this https://pkg.go.dev/mime#FormatMediaType

2022-11-04 22:27 UTC, wiedld commented on csv/dialect.go
> +		w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"%s\"; filename*=UTF-8''%s", d.ResultEncoderConfig.AttachmentFilename, d.ResultEncoderConfig.AttachmentFilename))
done.

2022-11-07 18:12 UTC, jsternberg approved these changes

2022-11-07 18:13 UTC, nathanielc approved these changes

2022-11-07 18:14 UTC, merged