feat(contrib/qxip/hash): add sha1, md5, base64
influxdata/flux pull request #5371
Opened 2023-01-21 20:05 UTC by lmangani

This PR extends the `contrib/qxip/hash` package with additional functions for `sha1`, `base64`, `md5`

- [x] Updated Documentation
- [ ] Extended Tests _(WIP)_

2023-01-23 18:06 UTC, sanderson requested changes
Thanks @lmangani! A few minor suggestions on the docs, but this looks great.

2023-01-23 18:06 UTC, sanderson commented on stdlib/contrib/qxip/hash/hash.flux
> +// b64 converts a string value to Base64 string.
```suggestion
// b64 converts a string value to a Base64 string.
```

2023-01-23 18:06 UTC, sanderson commented on stdlib/contrib/qxip/hash/hash.flux
> +// hmac converts a string value to an MD5 signed sha1 hash.
```suggestion
// hmac converts a string value to an MD5-signed SHA-1 hash.
```

2023-01-23 18:55 UTC, lmangani commented
Thank you so much @sanderson! Next attempt in line is an S3 HTTP client for flux 100% made in flux 🤞

2023-01-23 20:09 UTC, sanderson approved these changes

2023-01-23 20:40 UTC, gavincabbage approved these changes

2023-01-24 00:03 UTC, merged

2023-01-24 21:02 UTC, lmangani commented
@sanderson going paranoid mode temporarily: building with the latest flux master causes the following error, which related to this PR. I'm not sure if this is just about how I'm building my binary, but I'd rather be safe than sorry:

```
panic: missing builtin values [sha1 b64 md5 hmac], extra builtin values []

goroutine 1 [running]:
github.com/influxdata/flux/runtime.FinalizeBuiltIns(...)
        /home/runner/go/pkg/mod/github.com/influxdata/flux@v0.192.0/runtime/global.go:97
github.com/influxdata/flux/fluxinit.FluxInit(...)
        /home/runner/go/pkg/mod/github.com/influxdata/flux@v0.192.0/fluxinit/init.go:23
github.com/influxdata/flux/fluxinit/static.init.0()
        /home/runner/go/pkg/mod/github.com/influxdata/flux@v0.192.0/fluxinit/static/static.go:10 +0x3f
```

Did I miss something in the new code? The previous hash contrib was working fine. Apologies in advance!

2023-01-24 21:05 UTC, sanderson commented
@lmangani I think you need to regenerate the stdlib before you build.

```sh
> go generate ./stdlib ./libflux/go/libflux
> make generate
```

2023-01-24 21:13 UTC, lmangani commented
I think this could be caused by me building using the master for the go library and a release (v0.192.0) as the library (or vice versa) which does not include yet the changes? As long as this is a build issue only on my side, all is well... Thanks @sanderson